/**
 * Enemy archetypes. `sprite` is an index into assets/sprites/creatures.png
 * (Kenney Tiny Creatures, 16x16, 10 tiles per row).
 */
export const ENEMY_TYPES = {
  xiaogui: {
    id: "xiaogui",
    name: "小鬼",
    sprite: 10,
    hp: 22,
    speed: 74,
    radius: 10,
    damage: 5,
    attackCooldown: 1,
    behavior: "chase",
    score: 10,
    dropChance: 0.16,
  },
  yinbing: {
    id: "yinbing",
    name: "陰兵",
    sprite: 1,
    hp: 44,
    speed: 58,
    radius: 11,
    damage: 10,
    attackCooldown: 1.1,
    behavior: "chase",
    score: 18,
    dropChance: 0.22,
  },
  wugong: {
    id: "wugong",
    name: "蜈蚣精",
    sprite: 8,
    hp: 18,
    speed: 104,
    radius: 9,
    damage: 4,
    attackCooldown: 0.8,
    behavior: "chase",
    score: 14,
    dropChance: 0.12,
  },
  jiangshi: {
    id: "jiangshi",
    name: "殭屍",
    sprite: 0,
    hp: 78,
    speed: 42,
    radius: 12,
    damage: 14,
    attackCooldown: 1.3,
    behavior: "chase",
    score: 26,
    dropChance: 0.3,
  },
  huogui: {
    id: "huogui",
    name: "火鬼",
    sprite: 29,
    hp: 40,
    speed: 66,
    radius: 11,
    damage: 12,
    attackCooldown: 1.4,
    behavior: "charger",
    chargeRange: 190,
    chargeSpeed: 260,
    score: 24,
    dropChance: 0.26,
  },
  shuigui: {
    id: "shuigui",
    name: "水鬼",
    sprite: 26,
    hp: 34,
    speed: 50,
    radius: 11,
    damage: 9,
    attackCooldown: 1.8,
    behavior: "shooter",
    preferredRange: 168,
    projectile: { speed: 176, damage: 9, radius: 6, life: 2.4, kind: "water" },
    score: 22,
    dropChance: 0.26,
  },
  yanmei: {
    id: "yanmei",
    name: "眼魅",
    sprite: 5,
    hp: 26,
    speed: 44,
    radius: 10,
    damage: 11,
    attackCooldown: 2.1,
    behavior: "shooter",
    preferredRange: 210,
    projectile: { speed: 208, damage: 11, radius: 6, life: 2.2, kind: "gaze" },
    score: 24,
    dropChance: 0.24,
  },
};

export const BOSS_TYPES = {
  niutou: {
    id: "niutou",
    name: "牛頭將",
    sprite: 20,
    hp: 240,
    speed: 58,
    radius: 17,
    damage: 15,
    attackCooldown: 1.4,
    behavior: "charger",
    chargeRange: 260,
    chargeSpeed: 300,
    boss: true,
    slamCooldown: 5.6,
    slamRadius: 88,
    slamDamage: 16,
    summons: ["xiaogui"],
    summonCooldown: 9,
    summonCount: 2,
    score: 220,
  },
  heiwuchang: {
    id: "heiwuchang",
    name: "黑無常",
    sprite: 19,
    hp: 340,
    speed: 72,
    radius: 16,
    damage: 20,
    attackCooldown: 1.1,
    behavior: "chase",
    boss: true,
    slamCooldown: 4.4,
    slamRadius: 96,
    slamDamage: 22,
    summons: ["yinbing", "wugong"],
    summonCooldown: 8,
    summonCount: 3,
    score: 300,
  },
  guicha: {
    id: "guicha",
    name: "鬼差",
    sprite: 4,
    hp: 430,
    speed: 62,
    radius: 17,
    damage: 22,
    attackCooldown: 1.1,
    behavior: "shooter",
    preferredRange: 150,
    projectile: { speed: 214, damage: 16, radius: 8, life: 2.6, kind: "gaze" },
    boss: true,
    slamCooldown: 4.8,
    slamRadius: 104,
    slamDamage: 24,
    summons: ["yinbing", "shuigui"],
    summonCooldown: 8.5,
    summonCount: 2,
    score: 380,
  },
  guiwang: {
    id: "guiwang",
    name: "鬼王",
    sprite: 38,
    hp: 560,
    speed: 70,
    radius: 18,
    damage: 26,
    attackCooldown: 1,
    behavior: "charger",
    chargeRange: 300,
    chargeSpeed: 330,
    boss: true,
    slamCooldown: 4,
    slamRadius: 112,
    slamDamage: 28,
    summons: ["huogui", "jiangshi"],
    summonCooldown: 8,
    summonCount: 2,
    score: 480,
  },
  dasha: {
    id: "dasha",
    name: "廟口大煞",
    sprite: 96,
    hp: 780,
    speed: 76,
    radius: 19,
    damage: 30,
    attackCooldown: 0.95,
    behavior: "charger",
    chargeRange: 340,
    chargeSpeed: 360,
    boss: true,
    slamCooldown: 3.4,
    slamRadius: 124,
    slamDamage: 32,
    summons: ["yanmei", "huogui", "yinbing"],
    summonCooldown: 7,
    summonCount: 3,
    score: 720,
  },
};

export function getEnemyType(id) {
  const type = ENEMY_TYPES[id] || BOSS_TYPES[id];
  if (!type) throw new Error(`unknown enemy type: ${id}`);
  return type;
}

/** Build a live enemy from an archetype; `tuning` scales per-level difficulty. */
export function spawnEnemy(id, x, y, tuning = {}) {
  const type = getEnemyType(id);
  const hpScale = tuning.hpScale ?? 1;
  const damageScale = tuning.damageScale ?? 1;
  const speedScale = tuning.speedScale ?? 1;
  const maxHp = Math.round(type.hp * hpScale);
  return {
    uid: tuning.uid ?? 0,
    type: type.id,
    name: type.name,
    sprite: type.sprite,
    boss: Boolean(type.boss),
    x,
    y,
    vx: 0,
    vy: 0,
    radius: type.radius,
    hp: maxHp,
    maxHp,
    speed: type.speed * speedScale,
    damage: type.damage * damageScale,
    // Arriving enemies owe a full cooldown, so a spawn cannot hit on frame one.
    attackTimer: type.attackCooldown,
    attackCooldown: type.attackCooldown,
    behavior: type.behavior,
    chargeRange: type.chargeRange ?? 0,
    chargeSpeed: type.chargeSpeed ?? 0,
    chargeTimer: 0,
    chargeRest: 0,
    windUp: 0,
    preferredRange: type.preferredRange ?? 0,
    projectile: type.projectile ?? null,
    slamTimer: type.slamCooldown ?? 0,
    slamCooldown: type.slamCooldown ?? 0,
    slamRadius: type.slamRadius ?? 0,
    slamDamage: (type.slamDamage ?? 0) * damageScale,
    summons: type.summons ?? null,
    summonTimer: type.summonCooldown ?? 0,
    summonCooldown: type.summonCooldown ?? 0,
    summonCount: type.summonCount ?? 0,
    score: type.score,
    dropChance: type.dropChance ?? (type.boss ? 1 : 0.2),
    hurtFlash: 0,
    facing: 1,
    // Wall-following state: when the direct line is blocked the enemy sidesteps
    // along `avoidSign` instead of grinding against the obstacle forever.
    avoidTimer: 0,
    avoidLock: 0,
    avoidSign: (tuning.uid ?? 0) % 2 === 0 ? 1 : -1,
  };
}
